---
title: Beardlesshq.Github.Io
timezone: Europe/Stockholm
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Foo Company
email: hello@example.com
description: Short description
url: https://jekyll.example.com
twitter_username: twitter_user
github_org: github_org
markdown: kramdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- sass
- scss
- ".gitignore"
- ".rbenv-vars"
- wercker.yml
sass:
  sass_dir: _scss
  style: compressed
