---
title: beardless.io
timezone: Europe/Stockholm
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Beardless - Technology & Marketing Solutions
email: hello@beardless.io
description: Beardless AB provides marketing and technology solutions backed by modern
  processes and state of the art tools.
url: https://beardless.io
twitter_username: beardlesshq
github_org: beardlesshq
markdown: kramdown
exclude:
- README.md
- Gemfile
- Gemfile.lock
- sass
- scss
- ".gitignore"
- ".rbenv-vars"
- wercker.yml
sass:
  sass_dir: _scss
  style: compressed
